// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace mym_softcom.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514153143_AddAmountToReturnToWithdrawal")]
    partial class AddAmountToReturnToWithdrawal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("mym_softcom.Models.Cesion", b =>
                {
                    b.Property<int>("id_Cesiones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Cesiones"));

                    b.Property<decimal?>("cesion_cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("cesion_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("cesion_reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("deuda_antes_cesion")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("id_Client_Cedente")
                        .HasColumnType("int");

                    b.Property<int>("id_Client_Cesionario")
                        .HasColumnType("int");

                    b.Property<int>("id_Sales")
                        .HasColumnType("int");

                    b.Property<int>("id_Users")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("valor_pagado_antes_cesion")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_Cesiones");

                    b.HasIndex("id_Client_Cedente");

                    b.HasIndex("id_Client_Cesionario");

                    b.HasIndex("id_Sales");

                    b.HasIndex("id_Users");

                    b.ToTable("Cesions");
                });

            modelBuilder.Entity("mym_softcom.Models.Client", b =>
                {
                    b.Property<int>("id_Clients")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Clients"));

                    b.Property<int>("document")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("names")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("phone")
                        .HasColumnType("bigint");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("surnames")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_Clients");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("mym_softcom.Models.Detail", b =>
                {
                    b.Property<int>("id_Details")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Details"));

                    b.Property<decimal?>("covered_amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("id_Payments")
                        .HasColumnType("int");

                    b.Property<int>("id_Sales")
                        .HasColumnType("int");

                    b.Property<int>("number_quota")
                        .HasColumnType("int");

                    b.HasKey("id_Details");

                    b.HasIndex("id_Payments");

                    b.HasIndex("id_Sales");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("mym_softcom.Models.Discount", b =>
                {
                    b.Property<int>("id_Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Discount"));

                    b.Property<string>("apply_to")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp");

                    b.Property<decimal>("discount_amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("discount_date")
                        .HasColumnType("date");

                    b.Property<string>("discount_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("id_Clients")
                        .HasColumnType("int");

                    b.Property<int?>("id_Sales")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp");

                    b.HasKey("id_Discount");

                    b.HasIndex("id_Clients");

                    b.HasIndex("id_Sales");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("mym_softcom.Models.Lot", b =>
                {
                    b.Property<int>("id_Lots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Lots"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("block")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("id_Projects")
                        .HasColumnType("int");

                    b.Property<int>("lot_area")
                        .HasColumnType("int");

                    b.Property<int>("lot_number")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_Lots");

                    b.HasIndex("id_Projects");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("mym_softcom.Models.Material", b =>
                {
                    b.Property<int>("id_Materials")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Materials"));

                    b.Property<string>("category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("current_stock")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("minimum_stock")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("unit_cost")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("unit_of_measure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_Materials");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("mym_softcom.Models.MaterialCategory", b =>
                {
                    b.Property<int>("id_Categories")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Categories"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_Categories");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("material_categories", (string)null);
                });

            modelBuilder.Entity("mym_softcom.Models.MaterialMovement", b =>
                {
                    b.Property<int>("id_MaterialMovements")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_MaterialMovements"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("difference")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("id_Materials")
                        .HasColumnType("int");

                    b.Property<int?>("id_Projects")
                        .HasColumnType("int");

                    b.Property<string>("movement_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("new_stock")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("observations")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("old_stock")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("supplier")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("user_name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("id_MaterialMovements");

                    b.HasIndex("id_Materials");

                    b.HasIndex("id_Projects");

                    b.ToTable("material_movements", (string)null);
                });

            modelBuilder.Entity("mym_softcom.Models.Payment", b =>
                {
                    b.Property<int>("id_Payments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Payments"));

                    b.Property<decimal?>("amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("id_Sales")
                        .HasColumnType("int");

                    b.Property<DateTime>("payment_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_Payments");

                    b.HasIndex("id_Sales");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("mym_softcom.Models.Plan", b =>
                {
                    b.Property<int>("id_Plans")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Plans"));

                    b.Property<string>("name")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("number_quotas")
                        .HasColumnType("int");

                    b.HasKey("id_Plans");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("mym_softcom.Models.Project", b =>
                {
                    b.Property<int>("id_Projects")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Projects"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_Projects");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("mym_softcom.Models.Sale", b =>
                {
                    b.Property<int>("id_Sales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Sales"));

                    b.Property<string>("CustomQuotasJson")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("HouseInitialAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("HouseInitialPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(65,30)")
                        .HasDefaultValue(30m);

                    b.Property<decimal?>("LastQuotaValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NewQuotaValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OriginalQuotaValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PaymentPlanType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("Automatic");

                    b.Property<string>("RedistributedQuotaNumbers")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("RedistributionAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("RedistributionType")
                        .HasColumnType("longtext");

                    b.Property<int>("id_Clients")
                        .HasColumnType("int");

                    b.Property<int>("id_Lots")
                        .HasColumnType("int");

                    b.Property<int>("id_Plans")
                        .HasColumnType("int");

                    b.Property<int>("id_Users")
                        .HasColumnType("int");

                    b.Property<decimal?>("initial_payment")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("initial_payment_method")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("quota_value")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("sale_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Desistida','Escriturar')")
                        .HasDefaultValue("Active");

                    b.Property<decimal?>("total_debt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("total_raised")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("total_value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_Sales");

                    b.HasIndex("id_Clients");

                    b.HasIndex("id_Lots");

                    b.HasIndex("id_Plans");

                    b.HasIndex("id_Users");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("mym_softcom.Models.Transfer", b =>
                {
                    b.Property<int>("id_Transfers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Transfers"));

                    b.Property<string>("accounting_note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("amount_transferred")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_Clients")
                        .HasColumnType("int");

                    b.Property<int>("id_Sales_Destino")
                        .HasColumnType("int");

                    b.Property<int>("id_Sales_Origen")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("transfer_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("enum('Completo','Parcial')");

                    b.HasKey("id_Transfers");

                    b.HasIndex("id_Clients");

                    b.HasIndex("id_Sales_Destino");

                    b.HasIndex("id_Sales_Origen");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("mym_softcom.Models.TransferDetail", b =>
                {
                    b.Property<int>("id_TransferDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_TransferDetails"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_Transfers")
                        .HasColumnType("int");

                    b.Property<int>("number_quota")
                        .HasColumnType("int");

                    b.HasKey("id_TransferDetails");

                    b.HasIndex("id_Transfers");

                    b.ToTable("transfer_details", (string)null);
                });

            modelBuilder.Entity("mym_softcom.Models.User", b =>
                {
                    b.Property<int>("id_Users")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Users"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<bool>("Blockade")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hashed_Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nom_Users")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetTokenExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Salt")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tip_Users")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("id_Users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("mym_softcom.Models.Withdrawal", b =>
                {
                    b.Property<int>("id_Withdrawals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_Withdrawals"));

                    b.Property<decimal?>("amount_to_return")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("id_Sales")
                        .HasColumnType("int");

                    b.Property<decimal?>("penalty")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("withdrawal_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_Withdrawals");

                    b.HasIndex("id_Sales");

                    b.ToTable("Withdrawals");
                });

            modelBuilder.Entity("mym_softcom.Models.Cesion", b =>
                {
                    b.HasOne("mym_softcom.Models.Client", "client_cedente")
                        .WithMany()
                        .HasForeignKey("id_Client_Cedente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mym_softcom.Models.Client", "client_cesionario")
                        .WithMany()
                        .HasForeignKey("id_Client_Cesionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mym_softcom.Models.Sale", "sale")
                        .WithMany()
                        .HasForeignKey("id_Sales")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mym_softcom.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("id_Users")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client_cedente");

                    b.Navigation("client_cesionario");

                    b.Navigation("sale");

                    b.Navigation("user");
                });

            modelBuilder.Entity("mym_softcom.Models.Detail", b =>
                {
                    b.HasOne("mym_softcom.Models.Payment", "payment")
                        .WithMany()
                        .HasForeignKey("id_Payments")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mym_softcom.Models.Sale", "sale")
                        .WithMany()
                        .HasForeignKey("id_Sales")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("payment");

                    b.Navigation("sale");
                });

            modelBuilder.Entity("mym_softcom.Models.Discount", b =>
                {
                    b.HasOne("mym_softcom.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("id_Clients")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mym_softcom.Models.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("id_Sales");

                    b.Navigation("Client");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("mym_softcom.Models.Lot", b =>
                {
                    b.HasOne("mym_softcom.Models.Project", "project")
                        .WithMany()
                        .HasForeignKey("id_Projects")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("project");
                });

            modelBuilder.Entity("mym_softcom.Models.MaterialMovement", b =>
                {
                    b.HasOne("mym_softcom.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("id_Materials")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mym_softcom.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("id_Projects")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Material");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("mym_softcom.Models.Payment", b =>
                {
                    b.HasOne("mym_softcom.Models.Sale", "sale")
                        .WithMany()
                        .HasForeignKey("id_Sales")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sale");
                });

            modelBuilder.Entity("mym_softcom.Models.Sale", b =>
                {
                    b.HasOne("mym_softcom.Models.Client", "client")
                        .WithMany()
                        .HasForeignKey("id_Clients")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mym_softcom.Models.Lot", "lot")
                        .WithMany()
                        .HasForeignKey("id_Lots")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mym_softcom.Models.Plan", "plan")
                        .WithMany()
                        .HasForeignKey("id_Plans")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mym_softcom.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("id_Users")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("lot");

                    b.Navigation("plan");

                    b.Navigation("user");
                });

            modelBuilder.Entity("mym_softcom.Models.Transfer", b =>
                {
                    b.HasOne("mym_softcom.Models.Client", "client")
                        .WithMany()
                        .HasForeignKey("id_Clients")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mym_softcom.Models.Sale", "sale_destino")
                        .WithMany()
                        .HasForeignKey("id_Sales_Destino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mym_softcom.Models.Sale", "sale_origen")
                        .WithMany()
                        .HasForeignKey("id_Sales_Origen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("sale_destino");

                    b.Navigation("sale_origen");
                });

            modelBuilder.Entity("mym_softcom.Models.TransferDetail", b =>
                {
                    b.HasOne("mym_softcom.Models.Transfer", "transfer")
                        .WithMany("transfer_details")
                        .HasForeignKey("id_Transfers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("transfer");
                });

            modelBuilder.Entity("mym_softcom.Models.Withdrawal", b =>
                {
                    b.HasOne("mym_softcom.Models.Sale", "sale")
                        .WithMany()
                        .HasForeignKey("id_Sales")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sale");
                });

            modelBuilder.Entity("mym_softcom.Models.Transfer", b =>
                {
                    b.Navigation("transfer_details");
                });
#pragma warning restore 612, 618
        }
    }
}
